# PATH
# ----
# Base path
PATH=/usr/local/bin:\
     /usr/local/opt/ruby/bin:\
     /usr/local/lib/ruby/gems/2.6.0/bin:\
     /usr/local/sbin:\
     /usr/bin:\
     /bin:\
     /usr/sbin:\
     /sbin

export PATH


# Misc
# ----
# Set default browser
export BROWSER=open

# Set default editor
export EDITOR=/usr/local/bin/mvim

# Create pipenv virutalenvs in project folder
export PIPENV_VENV_IN_PROJECT=1

# Set path to GDAL drivers
export GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins

# Homebrew completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
fi

# Load in .bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
