# PATH
# ----
# Base path
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# Paths to additional binaries
PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.6/bin
PATH=$PATH:/Library/Frameworks/GDAL.framework/Versions/Current/Programs
PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin

export PATH


# Misc
# ----
# Set default browser
export BROWSER=open

# Homebrew completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
fi

# Load in .bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
