# PATH
# ----
# Base PATH
path=(/usr/local/bin
      /usr/local/opt/ruby/bin
      /usr/local/sbin
      /usr/bin
      /bin
      /usr/sbin
      /sbin)

export PATH


# Misc
# ----
# Set default browser
export BROWSER=open

# Set default editor
export EDITOR=/usr/local/bin/mvim

# Set path to GDAL drivers
export GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins
