# PATH
# ----
# Base PATH
path=(/usr/local/bin
      /usr/local/opt/ruby/bin
      $(/usr/local/opt/ruby/bin/gem environment gemdir)/bin
      /usr/local/opt/tcl-tk/bin
      /usr/local/sbin
      /usr/bin
      /bin
      /usr/sbin
      /sbin)

export PATH


# Misc
# ----
# Set default browser
export BROWSER=open

# Set default editor
export EDITOR=/usr/local/bin/mvim

# Homebrew
export HOMEBREW_BUNDLE_FILE=$HOME/.homebrew/Brewfile
export HOMEBREW_GITHUB_API_TOKEN=$( cat ~/.token/homebrew_github_api_token )

# Pyenv
eval "$(pyenv init --path)"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
