# PATH
# ----
# Base PATH
path=(/usr/local/bin
      /usr/local/opt/ruby/bin
      /usr/local/lib/ruby/gems/2.6.0/bin
      /usr/local/opt/tcl-tk/bin
      /usr/local/sbin
      /usr/bin
      /bin
      /usr/sbin
      /sbin
      /Applications/QGIS3.10.app/Contents/MacOS/bin)

export PATH


# Misc
# ----
# Set default browser
export BROWSER=open

# Set default editor
export EDITOR=/usr/local/bin/mvim

# Set default Homebrew Bundle Brewfile
export HOMEBREW_BUNDLE_FILE="$HOME/Development/Configuration/Mac-Config/Homebrew/Brewfile"

# Create pipenv virutalenvs in project folder
export PIPENV_VENV_IN_PROJECT=1
