# XDG Base Directoru
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# Zsh
export SHELL_SESSIONS_DISABLE=1
export ZDOTDIR=$HOME/.config/zsh
