# Options
# -------
setopt AUTO_CD  # Change to dir automatically

bindkey -v  # Use Vi mode

disable r  # Disable r builtin

HISTFILE="$XDG_STATE_HOME"/zsh/history
setopt SHARE_HISTORY

# Directory Stack
# ---------------
DIRSTACKSIZE=8
setopt AUTO_PUSHD  # Add old dir to dir stack
setopt PUSHD_IGNORE_DUPS  # Don't add dups to dir stack
setopt PUSHD_MINUS  # Reverts the +/- operators
setopt PUSHD_SILENT  # Do not print the dir stack
setopt PUSHD_TO_HOME  # pushd with no arguments goes to $Home

# Prompt
# ------
# Detect version control
autoload -Uz vcs_info

zstyle ':vcs_info:*' enable git  # Detect git only
zstyle ':vcs_info:*' disable-patterns "*/.git"  # Ignore .git folders
zstyle ':vcs_info:*' formats '%r [%b] ▶ '  # Prompt in repos
zstyle ':vcs_info:*' actionformats '%r [%b|%a] ▶ '  # During special actions
zstyle ':vcs_info:*' nvcsformats '▶ '  # Prompt in standard folders

precmd() { vcs_info }
setopt PROMPT_SUBST  # Prompt expansion
PROMPT='${vcs_info_msg_0_}'

# Completion
# ----------
[ -d "$XDG_CACHE_HOME"/zsh ] || mkdir -p "$XDG_CACHE_HOME"/zsh

zstyle ':completion:*' cache-path "$XDG_CACHE_HOME"/zsh/zcompcache

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle :compinstall filename '$XDG_CONFIG_HOME/zsh/.zshrc'

fpath=(
  $(brew --prefix)/share/zsh/site-functions
  $fpath
  $XDG_DATA_HOME/zsh/site-functions)

autoload -Uz compinit
compinit -i -d "$XDG_CACHE_HOME"/zsh/zcompdump-$ZSH_VERSION

# Search history
# --------------
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search  # Up
bindkey "^[[B" down-line-or-beginning-search  # Down

# Named directories
# -----------------
source $XDG_CONFIG_HOME/zsh/nmdirs

# Aliases
# -------
source $XDG_CONFIG_HOME/zsh/aliases
function xman() { open x-man-page://$@ ; }

# Tools
# -----
# fzf
source <(fzf --zsh)

_fzf_compgen_path() {
  fd --hidden --follow . "$1"
}

_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}
