# ZSH SETTINGS
#=============

# Options
# -------
setopt AUTO_CD  # Change to dir automatically

bindkey -v  # Use Vi mode

disable r  # Disable r builtin


# Directory Stack
# ---------------
DIRSTACKSIZE=8
setopt AUTO_PUSHD  # Add old dir to dir stack
setopt PUSHD_IGNORE_DUPS  # Don't add dups to dir stack
setopt PUSHD_MINUS  # Reverts the +/- operators
setopt PUSHD_SILENT  # Do not print the dir stack
setopt PUSHD_TO_HOME  # pushd with no arguments goes to $Home


# Prompt
# ------
# Detect version control
precmd() {
    vcs_info
}
autoload -Uz vcs_info

zstyle ':vcs_info:*' enable git  # Detect git only
zstyle ':vcs_info:*' disable-patterns "*/.git"  # Ignore .git folders

setopt PROMPT_SUBST  # Prompt expansion

zstyle ':vcs_info:*' formats '%r [%b] %# '  # Prompt in repos
zstyle ':vcs_info:*' actionformats '%r [%b|%a] %# '  # During special actions

zstyle ':vcs_info:*' nvcsformats '%# '  # Prompt in standard folders

PROMPT='${vcs_info_msg_0_}'


# Completion
# ----------
# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit -i
# End of lines added by compinstall

# pip completion
function _pip_completion {
  local words cword
  read -Ac words
  read -cn cword
  reply=( $( COMP_WORDS="$words[*]" \
             COMP_CWORD=$(( cword-1 )) \
             PIP_AUTO_COMPLETE=1 $words[1] 2>/dev/null ))
}
compctl -K _pip_completion pip pip3

# npm completion
_npm_completion() {
    local si=$IFS
    compadd -- $(COMP_CWORD=$((CURRENT-1)) \
                 COMP_LINE=$BUFFER \
                 COMP_POINT=0 \
                 npm completion -- "${words[@]}" \
                 2>/dev/null)
    IFS=$si
  }
compdef _npm_completion npm


# Search history
# --------------
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search  # Up
bindkey "^[[B" down-line-or-beginning-search  # Down


# Named directories
# -----------------
source ~/.nmdirs

# Aliases
# -------
source ~/.aliases

# Misc
# ----
# Pyenv
eval "$(pyenv init -)"
